// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShukiHelloWorld) DeepCopyInto(out *ShukiHelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShukiHelloWorld.
func (in *ShukiHelloWorld) DeepCopy() *ShukiHelloWorld {
	if in == nil {
		return nil
	}
	out := new(ShukiHelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShukiHelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShukiHelloWorldList) DeepCopyInto(out *ShukiHelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShukiHelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShukiHelloWorldList.
func (in *ShukiHelloWorldList) DeepCopy() *ShukiHelloWorldList {
	if in == nil {
		return nil
	}
	out := new(ShukiHelloWorldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShukiHelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShukiHelloWorldSpec) DeepCopyInto(out *ShukiHelloWorldSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShukiHelloWorldSpec.
func (in *ShukiHelloWorldSpec) DeepCopy() *ShukiHelloWorldSpec {
	if in == nil {
		return nil
	}
	out := new(ShukiHelloWorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShukiHelloWorldStatus) DeepCopyInto(out *ShukiHelloWorldStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShukiHelloWorldStatus.
func (in *ShukiHelloWorldStatus) DeepCopy() *ShukiHelloWorldStatus {
	if in == nil {
		return nil
	}
	out := new(ShukiHelloWorldStatus)
	in.DeepCopyInto(out)
	return out
}
